[general]
# define common settings here
flip_aug = false
color_aug = false
random_crop = false
shuffle_caption = false
caption_tag_dropout_rate = 0
caption_extension = ".txt"
keep_tokens = 1
keep_tokens_separator= "|||"

[[datasets]]
# define the first resolution here
batch_size = 1
enable_bucket = true
resolution = [1024, 1024]
min_bucket_reso = 256
max_bucket_reso = 1024 
bucket_reso_steps = 64   
bucket_no_upscale = false

  [[datasets.subsets]]
  image_dir = "/本地路径/训练集地址"
  num_repeats = 10